name: readotp_example

description: Demonstrates how to use the readotp plugin.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"       # Recommended for Flutter 3.22.7 (Dart 3.3.0+)
  flutter: ">=3.22.0"         # Match Flutter 3.22.7 minimum

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  readotp:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
