name: readotp
description: A flutter plugin that reads incoming SMS on device as a broadcast stream.
version: 1.0.1+3
homepage: "https://github.com/AkshayJayale/readotp.git"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.support_libs.readotp
        pluginClass: readotpPlugin

